wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: sCNN
dataset:
  desc: null
  value: Tumor Budding Hotspots
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691417207.062988
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.15.6
      8:
      - 5
